**Masters in Data Science | CUNY SPS | DATA 608 | Spring 2018.**

# Final Project

## Goal

To identify hidden patterns in the data set and find valuable information by the utilization of visualization techniques.

## Author:
  Duubar Villalobos Jimenez mydvtech@gmail.com
  
## About the data

The following is the information contained on this data set.

### Data Provided by:

+ Mayor’s Office of Data Analytics (MODA).

The Mayor’s Office of Data Analytics (MODA) is New York City’s civic intelligence center, allowing the City to aggregate and analyze data from across City agencies, to more effectively address crime, public safety, and quality of life issues. The office uses analytics tools to prioritize risk more strategically, deliver services more efficiently, enforce laws more effectively and increase transparency.

### Description:

The Multi Agency Permits dataset contains the permits data from two different data sources/exchanges:

  + DOB (Department of Buildings) Jobs Permits.
  + DOHMH (Department of Health and Mental Hygiene) Permits.

### What’s in this Dataset?

Columns in this Dataset

    Source
    License_Permit_Holder
    Business_Description
    License/Permit_Number
    Permit_Type_Description
    Permit_Subtype_Description
    Permit_Issuance_Date
    Permit_Expiration_Date
    Permit_Status_Date
    Permit_Status_Description
    Address
    Street
    City
    Zip_Code
    Borough
    Building_ID_No
    Borough_Block_Lot
    Latitude_WGS84
    Longitude_WGS84
    License/Permit_Holder_Name
    DOB_Skilled_Trades_Lic_Num
    DOB_Skilled_Trades_Lic_Type

**Dataset Identifier:** 24as-fxn4

**Source Domain:** data.cityofnewyork.us

**Category:** City Government.

**Attribution:** Mayor’s Office of Data Analytics (MODA).

**Owner:** NYC OpenData.

### Tools Employed:

The following are the tools employed for diverse processings.

  • R Studio
  • Python
  • Pandas
  • Plot.ly
  • Shine
  • Datashader
  • Dash
  • Jupyter Notebooks
  • Docker
  • EC2
  
 # References
 
http://www1.nyc.gov/site/analytics/index.page
https://moda-nyc.github.io/Project-Library/analytics/
https://moda-nyc.github.io/Project-Library/projects/
https://opendata.cityofnewyork.us/data/
https://data.cityofnewyork.us/City-Government/Multi-Agency-Permits/xfyi-uyt5
https://dev.socrata.com/foundry/data.cityofnewyork.us/24as-fxn4
